services:
  mongodb:
    image: mongo:8
    container_name: mentortrack-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mentortrack
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: